### ISSUE TITLE
Installation fails on OS X

### ISSUE THREAD

**Issue by qzb** [DreamLab/node-uriparser#12]
Installation on OS X (El Capitan) ends with following error:

```
$ npm install uriparser

> uriparser@2.1.2 install /Users/qzb/Workspace/other/dupa/node_modules/uriparser
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  ACTION binding_gyp_libparsers_target_build .
readlink: illegal option -- f
usage: readlink [-n] [file ...]
mkdir: /build/ngx_url_parser: Permission denied
build_deps.sh: line 12: cd: OLDPWD not set
mkdir: /build/uriparser: Permission denied
make: *** [.] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/qzb/Workspace/other/dupa/node_modules/uriparser
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN ENOENT ENOENT: no such file or directory, open '/Users/qzb/Workspace/other/dupa/package.json'
npm WARN EPACKAGEJSON dupa No description
npm WARN EPACKAGEJSON dupa No repository field.
npm WARN EPACKAGEJSON dupa No README data
npm WARN EPACKAGEJSON dupa No license field.
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "uriparser"
npm ERR! node v5.6.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! uriparser@2.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uriparser@2.1.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uriparser package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls uriparser
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/qzb/Workspace/other/dupa/npm-debug.log
```

**Comment by qzb** [comment]
Pull request #13 fixes the problem.
