### ISSUE TITLE
node-uriparser.cc compilation is failing with latest Node 5.1

### ISSUE THREAD

**Issue by mloskot** [DreamLab/node-uriparser#5]
I'm trying to install the uriparser package with `npm install uriparser` on Linux:

```
$ uname -a
Linux localhost 4.1.13-1-MANJARO #1 SMP PREEMPT Tue Nov 10 22:11:15 UTC 2015 x86_64 GNU/Linux
$ node -v
v5.1.0
$ npm -v
3.5.0
$ gcc --version
gcc (GCC) 5.2.0
```

and it is failing to build due to numerous compilation errors:

```
  CXX(target) Release/obj.target/uriparser/src/node-uriparser.o
../src/node-uriparser.cc:47:76: error: ‘NODE_PSYMBOL’ was not declared in this scope
 static v8::Persistent<v8::String> protocol_symbol = NODE_PSYMBOL("protocol");
                                                                            ^
../src/node-uriparser.cc:48:68: error: ‘NODE_PSYMBOL’ was not declared in this scope
 static v8::Persistent<v8::String> auth_symbol = NODE_PSYMBOL("auth");
                                                                    ^
../src/node-uriparser.cc:49:68: error: ‘NODE_PSYMBOL’ was not declared in this scope
 static v8::Persistent<v8::String> host_symbol = NODE_PSYMBOL("host");
                                                                    ^
../src/node-uriparser.cc:50:68: error: ‘NODE_PSYMBOL’ was not declared in this scope
 static v8::Persistent<v8::String> port_symbol = NODE_PSYMBOL("port");
                                                                    ^
../src/node-uriparser.cc:51:70: error: ‘NODE_PSYMBOL’ was not declared in this scope
 static v8::Persistent<v8::String> query_symbol = NODE_PSYMBOL("query");
                                                                      ^
../src/node-uriparser.cc:52:76: error: ‘NODE_PSYMBOL’ was not declared in this scope
 static v8::Persistent<v8::String> fragment_symbol = NODE_PSYMBOL("fragment");
                                                                            ^
../src/node-uriparser.cc:53:68: error: ‘NODE_PSYMBOL’ was not declared in this scope
 static v8::Persistent<v8::String> path_symbol = NODE_PSYMBOL("path");
                                                                    ^
../src/node-uriparser.cc:54:68: error: ‘NODE_PSYMBOL’ was not declared in this scope
 static v8::Persistent<v8::String> user_symbol = NODE_PSYMBOL("user");
                                                                    ^
../src/node-uriparser.cc:55:76: error: ‘NODE_PSYMBOL’ was not declared in this scope
 static v8::Persistent<v8::String> password_symbol = NODE_PSYMBOL("password");
                                                                            ^
../src/node-uriparser.cc:57:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
 static v8::Handle<v8::Value> parse(const v8::Arguments& args){
                                              ^
In file included from ../src/node-uriparser.cc:23:0:
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h: In function ‘v8::Handle<v8::Value> parse(const int&)’:
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:889:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/node-uriparser.cc:58:21: error: within this context
     v8::HandleScope scope;
                     ^
../src/node-uriparser.cc:62:14: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
     if (args.Length() == 0 || !args[0]->IsString()) {
              ^
../src/node-uriparser.cc:62:38: error: invalid types ‘const int[int]’ for array subscript
     if (args.Length() == 0 || !args[0]->IsString()) {
                                      ^
../src/node-uriparser.cc:63:16: error: ‘ThrowException’ is not a member of ‘v8’
         return v8::ThrowException(v8::Exception::TypeError(v8::String::New("First argument has to be string")));
                ^
../src/node-uriparser.cc:63:60: error: ‘New’ is not a member of ‘v8::String’
         return v8::ThrowException(v8::Exception::TypeError(v8::String::New("First argument has to be string")));
                                                            ^
../src/node-uriparser.cc:66:15: error: invalid types ‘const int[int]’ for array subscript
     if (args[1]->IsNumber()) {
               ^
../src/node-uriparser.cc:67:48: error: invalid types ‘const int[int]’ for array subscript
         opts = static_cast<parseOptions>(args[1]->Int32Value());
                                                ^
../src/node-uriparser.cc:70:5: error: ‘AsciiValue’ is not a member of ‘v8::String’
     v8::String::AsciiValue url (args[0]->ToString());
     ^
../src/node-uriparser.cc:72:9: error: ‘url’ was not declared in this scope
     if (url.length() == 0) {
         ^
../src/node-uriparser.cc:73:16: error: ‘ThrowException’ is not a member of ‘v8’
         return v8::ThrowException(v8::Exception::TypeError(v8::String::New("String mustn't be empty")));
                ^
../src/node-uriparser.cc:73:60: error: ‘New’ is not a member of ‘v8::String’
         return v8::ThrowException(v8::Exception::TypeError(v8::String::New("String mustn't be empty")));
                                                            ^
../src/node-uriparser.cc:81:31: error: ‘url’ was not declared in this scope
     if (uriParseUriA(&state, *url) != URI_SUCCESS) {
                               ^
../src/node-uriparser.cc:82:16: error: ‘ThrowException’ is not a member of ‘v8’
         return v8::ThrowException(v8::Exception::Error(v8::String::New("Unable to parse given url")));
                ^
../src/node-uriparser.cc:82:56: error: ‘New’ is not a member of ‘v8::String’
         return v8::ThrowException(v8::Exception::Error(v8::String::New("Unable to parse given url")));
                                                        ^
../src/node-uriparser.cc:86:50: error: no matching function for call to ‘v8::Object::New()’
     v8::Local<v8::Object> data = v8::Object::New();
                                                  ^
In file included from ../src/node-uriparser.cc:23:0:
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2930:24: note: candidate: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2930:24: note:   candidate expects 1 argument, 0 provided
../src/node-uriparser.cc:31:16: error: ‘ThrowException’ is not a member of ‘v8’
         return v8::ThrowException(v8::Exception::SyntaxError(v8::String::New("Bad string given"))); \
                ^
../src/node-uriparser.cc:89:9: note: in expansion of macro ‘THROW_IF_NULL’
         THROW_IF_NULL(uri.scheme)
         ^
../src/node-uriparser.cc:31:62: error: ‘New’ is not a member of ‘v8::String’
         return v8::ThrowException(v8::Exception::SyntaxError(v8::String::New("Bad string given"))); \
                                                              ^
../src/node-uriparser.cc:89:9: note: in expansion of macro ‘THROW_IF_NULL’
         THROW_IF_NULL(uri.scheme)
         ^
../src/node-uriparser.cc:91:36: error: ‘New’ is not a member of ‘v8::String’
         data->Set(protocol_symbol, v8::String::New(uri.scheme.first, (uri.scheme.afterLast - uri.scheme.first) + 1), attrib);
                                    ^
../src/node-uriparser.cc:31:16: error: ‘ThrowException’ is not a member of ‘v8’
         return v8::ThrowException(v8::Exception::SyntaxError(v8::String::New("Bad string given"))); \
                ^
../src/node-uriparser.cc:95:9: note: in expansion of macro ‘THROW_IF_NULL’
         THROW_IF_NULL(uri.userInfo)
         ^
../src/node-uriparser.cc:31:62: error: ‘New’ is not a member of ‘v8::String’
         return v8::ThrowException(v8::Exception::SyntaxError(v8::String::New("Bad string given"))); \
                                                              ^
../src/node-uriparser.cc:95:9: note: in expansion of macro ‘THROW_IF_NULL’
         THROW_IF_NULL(uri.userInfo)
         ^
../src/node-uriparser.cc:105:62: error: no matching function for call to ‘v8::Object::New()’
             v8::Local<v8::Object> authData = v8::Object::New();
                                                              ^
In file included from ../src/node-uriparser.cc:23:0:
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2930:24: note: candidate: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2930:24: note:   candidate expects 1 argument, 0 provided
../src/node-uriparser.cc:106:40: error: ‘New’ is not a member of ‘v8::String’
             authData->Set(user_symbol, v8::String::New(authUser), attrib);
                                        ^
../src/node-uriparser.cc:107:44: error: ‘New’ is not a member of ‘v8::String’
             authData->Set(password_symbol, v8::String::New(authPassword), attrib);
                                            ^
../src/node-uriparser.cc:109:52: error: no matching function for call to ‘v8::Object::Set(v8::Persistent<v8::String>&, v8::Local<v8::Object>&, v8::PropertyAttribute&)’
             data->Set(auth_symbol, authData, attrib);
                                                    ^
In file included from /home/mloskot/.node-gyp/5.1.0/include/node/v8.h:23:0,
                 from ../src/node-uriparser.cc:23:
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2587:26: note: candidate: bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)
                     bool Set(Local<Value> key, Local<Value> value));
                          ^
/home/mloskot/.node-gyp/5.1.0/include/node/v8config.h:347:48: note: in definition of macro ‘V8_DEPRECATE_SOON’
 #define V8_DEPRECATE_SOON(message, declarator) declarator
                                                ^
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2587:26: note:   candidate expects 2 arguments, 3 provided
                     bool Set(Local<Value> key, Local<Value> value));
                          ^
/home/mloskot/.node-gyp/5.1.0/include/node/v8config.h:347:48: note: in definition of macro ‘V8_DEPRECATE_SOON’
 #define V8_DEPRECATE_SOON(message, declarator) declarator
                                                ^
In file included from ../src/node-uriparser.cc:23:0:
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2588:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2588:37: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::String>’ to ‘v8::Local<v8::Context>’
In file included from /home/mloskot/.node-gyp/5.1.0/include/node/v8.h:23:0,
                 from ../src/node-uriparser.cc:23:
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2592:26: note: candidate: bool v8::Object::Set(uint32_t, v8::Local<v8::Value>)
                     bool Set(uint32_t index, Local<Value> value));
                          ^
/home/mloskot/.node-gyp/5.1.0/include/node/v8config.h:347:48: note: in definition of macro ‘V8_DEPRECATE_SOON’
 #define V8_DEPRECATE_SOON(message, declarator) declarator
                                                ^
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2592:26: note:   candidate expects 2 arguments, 3 provided
                     bool Set(uint32_t index, Local<Value> value));
                          ^
/home/mloskot/.node-gyp/5.1.0/include/node/v8config.h:347:48: note: in definition of macro ‘V8_DEPRECATE_SOON’
 #define V8_DEPRECATE_SOON(message, declarator) declarator
                                                ^
In file included from ../src/node-uriparser.cc:23:0:
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2593:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2593:37: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::String>’ to ‘v8::Local<v8::Context>’
../src/node-uriparser.cc:31:16: error: ‘ThrowException’ is not a member of ‘v8’
         return v8::ThrowException(v8::Exception::SyntaxError(v8::String::New("Bad string given"))); \
                ^
../src/node-uriparser.cc:114:9: note: in expansion of macro ‘THROW_IF_NULL’
         THROW_IF_NULL(uri.hostText)
         ^
../src/node-uriparser.cc:31:62: error: ‘New’ is not a member of ‘v8::String’
         return v8::ThrowException(v8::Exception::SyntaxError(v8::String::New("Bad string given"))); \
                                                              ^
../src/node-uriparser.cc:114:9: note: in expansion of macro ‘THROW_IF_NULL’
         THROW_IF_NULL(uri.hostText)
         ^
../src/node-uriparser.cc:115:32: error: ‘New’ is not a member of ‘v8::String’
         data->Set(host_symbol, v8::String::New(uri.hostText.first, uri.hostText.afterLast - uri.hostText.first), attrib);
                                ^
../src/node-uriparser.cc:31:16: error: ‘ThrowException’ is not a member of ‘v8’
         return v8::ThrowException(v8::Exception::SyntaxError(v8::String::New("Bad string given"))); \
                ^
../src/node-uriparser.cc:119:9: note: in expansion of macro ‘THROW_IF_NULL’
         THROW_IF_NULL(uri.portText)
         ^
../src/node-uriparser.cc:31:62: error: ‘New’ is not a member of ‘v8::String’
         return v8::ThrowException(v8::Exception::SyntaxError(v8::String::New("Bad string given"))); \
                                                              ^
../src/node-uriparser.cc:119:9: note: in expansion of macro ‘THROW_IF_NULL’
         THROW_IF_NULL(uri.portText)
         ^
../src/node-uriparser.cc:120:32: error: ‘New’ is not a member of ‘v8::String’
         data->Set(port_symbol, v8::String::New(uri.portText.first, uri.portText.afterLast - uri.portText.first), attrib);
                                ^
../src/node-uriparser.cc:31:16: error: ‘ThrowException’ is not a member of ‘v8’
         return v8::ThrowException(v8::Exception::SyntaxError(v8::String::New("Bad string given"))); \
                ^
../src/node-uriparser.cc:124:9: note: in expansion of macro ‘THROW_IF_NULL’
         THROW_IF_NULL(uri.query)
         ^
../src/node-uriparser.cc:31:62: error: ‘New’ is not a member of ‘v8::String’
         return v8::ThrowException(v8::Exception::SyntaxError(v8::String::New("Bad string given"))); \
                                                              ^
../src/node-uriparser.cc:124:9: note: in expansion of macro ‘THROW_IF_NULL’
         THROW_IF_NULL(uri.query)
         ^
../src/node-uriparser.cc:134:59: error: no matching function for call to ‘v8::Object::New()’
         v8::Local<v8::Object> queryData = v8::Object::New();
                                                           ^
In file included from ../src/node-uriparser.cc:23:0:
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2930:24: note: candidate: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2930:24: note:   candidate expects 1 argument, 0 provided
../src/node-uriparser.cc:151:50: error: ‘New’ is not a member of ‘v8::String’
                 v8::Local<v8::String> queryKey = v8::String::New(queryParamKey);
                                                  ^
../src/node-uriparser.cc:153:46: error: ‘New’ is not a member of ‘v8::String’
                     queryData->Set(queryKey, v8::String::New(queryParamValue ? queryParamValue : ""), attrib);
                                              ^
../src/node-uriparser.cc:163:41: error: ‘New’ is not a member of ‘v8::String’
             v8::Local<v8::String> key = v8::String::New(it->first.c_str());
                                         ^
../src/node-uriparser.cc:164:67: error: invalid conversion from ‘std::list<const char*>::size_type {aka long unsigned int}’ to ‘v8::Isolate*’ [-fpermissive]
             v8::Local<v8::Array> arrVal = v8::Array::New(vals.size());
                                                                   ^
In file included from ../src/node-uriparser.cc:23:0:
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2962:23: note:   initializing argument 1 of ‘static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)’
   static Local<Array> New(Isolate* isolate, int length = 0);
                       ^
../src/node-uriparser.cc:167:32: error: ‘New’ is not a member of ‘v8::String’
                 arrVal->Set(i, v8::String::New(*it2));
                                ^
../src/node-uriparser.cc:175:54: error: no matching function for call to ‘v8::Object::Set(v8::Persistent<v8::String>&, v8::Local<v8::Object>&, v8::PropertyAttribute&)’
             data->Set(query_symbol, queryData, attrib);
                                                      ^
In file included from /home/mloskot/.node-gyp/5.1.0/include/node/v8.h:23:0,
                 from ../src/node-uriparser.cc:23:
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2587:26: note: candidate: bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)
                     bool Set(Local<Value> key, Local<Value> value));
                          ^
/home/mloskot/.node-gyp/5.1.0/include/node/v8config.h:347:48: note: in definition of macro ‘V8_DEPRECATE_SOON’
 #define V8_DEPRECATE_SOON(message, declarator) declarator
                                                ^
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2587:26: note:   candidate expects 2 arguments, 3 provided
                     bool Set(Local<Value> key, Local<Value> value));
                          ^
/home/mloskot/.node-gyp/5.1.0/include/node/v8config.h:347:48: note: in definition of macro ‘V8_DEPRECATE_SOON’
 #define V8_DEPRECATE_SOON(message, declarator) declarator
                                                ^
In file included from ../src/node-uriparser.cc:23:0:
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2588:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2588:37: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::String>’ to ‘v8::Local<v8::Context>’
In file included from /home/mloskot/.node-gyp/5.1.0/include/node/v8.h:23:0,
                 from ../src/node-uriparser.cc:23:
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2592:26: note: candidate: bool v8::Object::Set(uint32_t, v8::Local<v8::Value>)
                     bool Set(uint32_t index, Local<Value> value));
                          ^
/home/mloskot/.node-gyp/5.1.0/include/node/v8config.h:347:48: note: in definition of macro ‘V8_DEPRECATE_SOON’
 #define V8_DEPRECATE_SOON(message, declarator) declarator
                                                ^
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2592:26: note:   candidate expects 2 arguments, 3 provided
                     bool Set(uint32_t index, Local<Value> value));
                          ^
/home/mloskot/.node-gyp/5.1.0/include/node/v8config.h:347:48: note: in definition of macro ‘V8_DEPRECATE_SOON’
 #define V8_DEPRECATE_SOON(message, declarator) declarator
                                                ^
In file included from ../src/node-uriparser.cc:23:0:
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2593:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:2593:37: note:   no known conversion for argument 1 from ‘v8::Persistent<v8::String>’ to ‘v8::Local<v8::Context>’
../src/node-uriparser.cc:31:16: error: ‘ThrowException’ is not a member of ‘v8’
         return v8::ThrowException(v8::Exception::SyntaxError(v8::String::New("Bad string given"))); \
                ^
../src/node-uriparser.cc:183:9: note: in expansion of macro ‘THROW_IF_NULL’
         THROW_IF_NULL(uri.fragment);
         ^
../src/node-uriparser.cc:31:62: error: ‘New’ is not a member of ‘v8::String’
         return v8::ThrowException(v8::Exception::SyntaxError(v8::String::New("Bad string given"))); \
                                                              ^
../src/node-uriparser.cc:183:9: note: in expansion of macro ‘THROW_IF_NULL’
         THROW_IF_NULL(uri.fragment);
         ^
../src/node-uriparser.cc:184:36: error: ‘New’ is not a member of ‘v8::String’
         data->Set(fragment_symbol, v8::String::New(uri.fragment.first, uri.fragment.afterLast - uri.fragment.first), attrib);
                                    ^
../src/node-uriparser.cc:31:16: error: ‘ThrowException’ is not a member of ‘v8’
         return v8::ThrowException(v8::Exception::SyntaxError(v8::String::New("Bad string given"))); \
                ^
../src/node-uriparser.cc:193:13: note: in expansion of macro ‘THROW_IF_NULL’
             THROW_IF_NULL(pathHead->text)
             ^
../src/node-uriparser.cc:31:62: error: ‘New’ is not a member of ‘v8::String’
         return v8::ThrowException(v8::Exception::SyntaxError(v8::String::New("Bad string given"))); \
                                                              ^
../src/node-uriparser.cc:193:13: note: in expansion of macro ‘THROW_IF_NULL’
             THROW_IF_NULL(pathHead->text)
             ^
../src/node-uriparser.cc:226:32: error: ‘New’ is not a member of ‘v8::String’
         data->Set(path_symbol, v8::String::New(p), attrib);
                                ^
../src/node-uriparser.cc:229:32: error: ‘New’ is not a member of ‘v8::String’
         data->Set(path_symbol, v8::String::New("/"), attrib);
                                ^
../src/node-uriparser.cc:234:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(data);
                  ^
In file included from ../src/node-uriparser.cc:23:0:
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h: In function ‘void init(v8::Handle<v8::Object>)’:
/home/mloskot/.node-gyp/5.1.0/include/node/v8.h:889:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/node-uriparser.cc:238:21: error: within this context
     v8::HandleScope scope;
                     ^
../src/node-uriparser.cc:240:43: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [6], v8::Handle<v8::Value> (&)(const int&))’
     NODE_SET_METHOD(target, "parse", parse);
                                           ^
In file included from ../src/node-uriparser.cc:24:0:
/home/mloskot/.node-gyp/5.1.0/include/node/node.h:236:13: note: candidate: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
 inline void NODE_SET_METHOD(const TypeName& recv,
             ^
/home/mloskot/.node-gyp/5.1.0/include/node/node.h:236:13: note:   template argument deduction/substitution failed:
../src/node-uriparser.cc:240:43: note:   cannot convert ‘parse’ (type ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’) to type ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’
     NODE_SET_METHOD(target, "parse", parse);
                                           ^
uriparser.target.mk:95: recipe for target 'Release/obj.target/uriparser/src/node-uriparser.o' failed
make: *** [Release/obj.target/uriparser/src/node-uriparser.o] Error 1
make: Leaving directory '/home/mloskot/dev/node-url-test/node_modules/uriparser/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.13-1-MANJARO
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mloskot/dev/node-url-test/node_modules/uriparser
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
...
```

The V8 version is:
```
$ cat /usr/include/node/v8-version.h | grep "define V8_.*"
#define V8_INCLUDE_VERSION_H_
#define V8_MAJOR_VERSION 4
#define V8_MINOR_VERSION 6
#define V8_BUILD_NUMBER 85
#define V8_PATCH_LEVEL 31
#define V8_IS_CANDIDATE_VERSION 0
```

**Comment by kuebk** [comment]
Hi,

We are currently working on this issue: https://github.com/DreamLab/node-uriparser/pull/6. New version is going to be published soon. :)

Thanks.

**Comment by Aldor007** [comment]
HI
We have published new version of uriparser. Try it out. ;)
